### ISSUE TITLE
Non-deterministic Tokenizations with BPE

### ISSUE THREAD

**Issue by jafioti** [huggingface/tokenizers#644] opened 2021-03-02 04:40 UTC
I've been working with Tokenizers in rust and have ran into non-deterministic tokenizations when using the BPE tokenizer.

Here is my full function:
`use tokenizers::tokenizer::{Tokenizer, EncodeInput};
    use tokenizers::models::bpe::BPE;
    
    let bpe_builder = BPE::from_files("bpe_vocab.json", "bpe_merges.txt");
    let bpe = bpe_builder
        .dropout(0.1)
        .unk_token("[UNK]".into())
        .build().expect("BPE Tokenizer failed to build!");

    let tokenizer = Tokenizer::new(Box::new(bpe));
    // Convert into EncodeInputs
    let mut encode_inputs: Vec<EncodeInput> = Vec::with_capacity(strings.len());
    for string in strings.iter() {
        encode_inputs.push(EncodeInput::Single(string.into()));
    }
    // Tokenize
    let encodings = tokenizer.encode_batch(encode_inputs, false).expect("BPE tokenization failed!");
    // Convert back to strings
    let mut tokens: Vec<Vec<String>> = Vec::with_capacity(strings.len());
    for encoding in encodings.iter() {
        tokens.push(encoding.get_tokens().to_vec());
    }
    tokens`

When I tokenize "Hello, how are you?" I get multiple different tokenizations such as  
["Hello", ",", " ", "how", " ", "are", " ", "you", "?"]
as well as
["He", "llo", ",", " ", "how", " ", "are", " ", "you", "?"]
without making any changes to the code whatsoever.

Is this expected or is there an option to enable deterministic behavior for a speed cost?

**Comment by Narsil** [comment] 2021-03-02 10:44
HI @jafioti ,

You are using `dropout(0,1)` . so it's actually by design that it's skipping some merges sometimes.
During training, having a dropout can yield improvements overall because it makes the training more robust to vocabulary changes, typos, spelling errors in the original string.

If you want deterministic, simply remove the dropout.

Closing this. Feel free to re-open if this didn't answer your problem.

**Closed by Narsil** 2021-03-02 10:44 UTC
