### ISSUE TITLE
[Bug] Error in saving tokenizer after adding tokens

### ISSUE THREAD

**Issue by ahnjaewoo** [huggingface/tokenizers#189] opened 2020-03-06 04:33 UTC
Below is a part of the code with an error.
```
from tokenizers import SentencePieceBPETokenizer

tokenizer = SentencePieceBPETokenizer()
tokenizer.train([data_dir], vocab_size=32000)
tokenizer.add_tokens(['<some tokens>'])
tokenizer.save('.')  # save it to ['vocab.json', 'merges.txt']
```
After I saved the tokenizer, I found that `vocab.json` file didn't contain any tokens (i.e., `<some tokens>` above).
I think this `save` method should be improved.
Thanks.

**Comment by n1t0** [comment] 2020-04-22 17:09
Duplicate of https://github.com/huggingface/tokenizers/issues/15

**Closed by n1t0** 2020-04-22 17:09 UTC
