### ISSUE TITLE
Tokenizers | TypeError: not a string

### ISSUE THREAD

**Issue by danielbellhv** [huggingface/tokenizers#878] opened 2022-01-14 12:38 UTC
I've read up documentation, such as AlbertTokenizer, to understand parameters.

Code:
```python
# define the tokenizer
print('-- configs.output_dir --')
print(configs.output_dir)
print(type(configs.output_dir))
print('-- configs.do_lower_case --')
print(configs.do_lower_case)
print(type(configs.do_lower_case))
if 'albert' in MODEL_NAME:
    tokenizer = AlbertTokenizer.from_pretrained(
        pretrained_model_name_or_path="./MRPC/"
    )
```

Traceback:
```
-- configs.output_dir --
./MRPC/
<class 'str'>
-- configs.do_lower_case --
True
<class 'bool'>
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-14-a1e7d60f16fd> in <module>
    147 if 'albert' in MODEL_NAME:
    148     tokenizer = AlbertTokenizer.from_pretrained(
--> 149         pretrained_model_name_or_path="./MRPC/"
    150     )
    151 else:

~/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/transformers/tokenization_utils_base.py in from_pretrained(cls, pretrained_model_name_or_path, *init_inputs, **kwargs)
   1752             use_auth_token=use_auth_token,
   1753             cache_dir=cache_dir,
-> 1754             **kwargs,
   1755         )
   1756 

~/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/transformers/tokenization_utils_base.py in _from_pretrained(cls, resolved_vocab_files, pretrained_model_name_or_path, init_configuration, use_auth_token, cache_dir, *init_inputs, **kwargs)
   1880         # Instantiate tokenizer.
   1881         try:
-> 1882             tokenizer = cls(*init_inputs, **init_kwargs)
   1883         except OSError:
   1884             raise OSError(

~/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/transformers/models/albert/tokenization_albert.py in __init__(self, vocab_file, do_lower_case, remove_space, keep_accents, bos_token, eos_token, unk_token, sep_token, pad_token, cls_token, mask_token, sp_model_kwargs, **kwargs)
    179 
    180         self.sp_model = spm.SentencePieceProcessor(**self.sp_model_kwargs)
--> 181         self.sp_model.Load(vocab_file)
    182 
    183     @property

~/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/sentencepiece/__init__.py in Load(self, model_file, model_proto)
    365       if model_proto:
    366         return self.LoadFromSerializedProto(model_proto)
--> 367       return self.LoadFromFile(model_file)
    368 
    369 

~/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/sentencepiece/__init__.py in LoadFromFile(self, arg)
    169 
    170     def LoadFromFile(self, arg):
--> 171         return _sentencepiece.SentencePieceProcessor_LoadFromFile(self, arg)
    172 
    173     def DecodeIdsWithCheck(self, ids):

TypeError: not a string
```

**Comment by danielbellhv** [comment] 2022-01-14 12:39
I've already setup a [SO post](https://stackoverflow.com/questions/70709572/typeerror-not-a-string-parameters-in-autotokenizer-from-pretrained) regarding this.

**Comment by Narsil** [comment] 2022-01-14 13:25
Your comment is missing the full code to reproduce.

However, looking at the code you are using `AlbertTokenizer` not `AlbertTokenizerFast` so you are using the "slow" version of tokenizers which use sentencepiece in that case. Meaning the issue is not meant for this repo (which are `..Fast` tokenizers).

Closing this here, this issues belong in `transformers` IMO.

**Comment by danielbellhv** [comment] 2022-01-14 13:34
Hi @Narsil, I get the same error when importing and using `AlbertTokenizerFast` too

**Comment by danielbellhv** [comment] 2022-01-14 14:05
Passing `albert-base-v2` as the only parameter solves this.

**Comment by Narsil** [comment] 2022-01-14 15:06
What is in your `./MRPC` directory ? Could you share its contents ?

You are trying to import from local save of the model. If that directory is missing a file then it won't work.
`spiece.model` seems like it should be in there for instance.

**Comment by danielbellhv** [comment] 2022-01-14 15:09
`MRPC/`:
```python
from os import listdir
from os.path import isfile, join
​
mypath = './MRPC/'
onlyfiles = [f for f in listdir(mypath) if isfile(join(mypath, f))]
onlyfiles
---

['tokenizer_config.json',
 'special_tokens_map.json',
 'pytorch_model.bin',
 'config.json',
 'training_args.bin',
 'added_tokens.json',
 'vocab.txt']
```

**Comment by Narsil** [comment] 2022-01-14 16:02
Can you try doing `AutoTokenizer.fom_pretrained("./MRPC")` ?
Maybe the `tokenizer` is different than `Albert`? 


Since there is no `spiece.model` a non fast is unlikely to work.

**Comment by MrSworder** [comment] 2022-07-03 12:51
Same error. I think it because of spiece.model. It will be OK if "spiece.model" in the fold. But some model has not this file.  Why it can't be initiated by vocab.txt or tokenizer_config.json?

**Comment by Narsil** [comment] 2022-07-15 15:39
Because `spiece.model` actually contains the logic to do the tokenization.

Closing this as again this doesn't belong here but in `transformers`.

**Closed by Narsil** 2022-07-15 15:39 UTC
