### ISSUE TITLE
How to encode multiple sentences？

### ISSUE THREAD

**Issue by liuhe6** [huggingface/tokenizers#778] opened 2021-08-18 03:30 UTC
Hi, I know that tokenizers can encode a single sentence("[CLS] $A [SEP]") or sentence pair ("[CLS] $A [SEP] $B [SEP]").
But how to encode more sentence? 
For example :
sentence1 = "a b c d", sentence2 = "e f g h", sentence3 = "i j k l"
how can I get " [CLS] a b c d [SEP] e f g h [SEP]  i j k l [SEP]"?

**Comment by fcakyon** [comment] 2021-11-09 12:05
Any updates on this @Narsil ?

**Comment by Narsil** [comment] 2021-11-09 12:53
See #804, closing this as a duplicate.

**Closed by Narsil** 2021-11-09 12:53 UTC

**Comment by hrdxwandg** [comment] 2022-11-17 07:40
any solutions on this @liuhe6 @Narsil

**Comment by Narsil** [comment] 2022-11-17 10:03
It's now "possible" technically, although I didn't do anything to implement it anywhere.
Please let's use the other issue for discussion.

**Comment by hrdxwandg** [comment] 2022-11-18 01:29
> It's now "possible" technically, although I didn't do anything to implement it anywhere. Please let's use the other issue for discussion.

OK, the new issue https://github.com/huggingface/tokenizers/issues/1111

**Comment by Narsil** [comment] 2022-11-18 09:14
I mean the other issue #804 which this issue is a duplicate of.
