### ISSUE TITLE
tokenizer.train with strings not files

### ISSUE THREAD

**Issue by geg00** [huggingface/tokenizers#299] opened 2020-06-09 22:48 UTC
I'm trying to train a tokenizer with a bunch of text files in Apache Tika json format 

I just want to train it with text not with file names.
file1 = json.load(open('json file.json, 'rb'))

The content is stored here
file1[0]['X-TIKA:content']

I want to send the content to train but 
tokenizer.train only allows me to use a list of files not text.

I can extract the content and then save it again but that's not really the case.

Is there any way to feed strings to the tokenizer.train???

**Comment by sayakpaul** [comment] 2020-06-13 04:29
I have a similar use case. In my case, I am trying to pass on an array of sentences actually which look like so:

![image](https://user-images.githubusercontent.com/22957388/84559893-69b09c80-ad5c-11ea-99fd-f70e819354f0.png)

I am using `ByteLevelBPETokenizer` and here's why I am trying to fit it to the data:

```python
training_data = np.array(stories_df['sentence']).reshape(-1, 1)
tokenizer.train(training_data, vocab_size=20000)
```

Any directions would be really helpful.

**Comment by n1t0** [comment] 2020-06-15 12:36
This is not possible at the moment, but indeed we should clearly support this use case.

**Comment by n1t0** [comment] 2020-10-20 21:28
Duplicate of #198

**Closed by n1t0** 2020-10-20 21:28 UTC

**Comment by klxu03** [comment] 2024-05-01 23:47
Is it still not supported yet?
