### ISSUE TITLE
Giving invalid file location to train a tokenizer results in exiting the process and fatal runtime error

### ISSUE THREAD

**Issue by llStringll** [huggingface/tokenizers#349] opened 2020-07-17 19:13 UTC
While training a tokenizer like so:
```
from tokenizers import ByteLevelBPETokenizer as bpe
tok = bpe(add_prefix_space=True, lowercase=True)
tok.train([train_corpus], vocab_size=16000, special_tokens=["[PAD]", "[CLS]", "[SEP]", "[UNK]"])
```
If the train_corpus is invalid, i.e., the file does not exist, it exhibits the under shown behavior, the error could be handled in a better way.
```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', /__w/tokenizers/tokenizers/tokenizers/src/tokenizer/mod.rs:593:29
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fatal runtime error: failed to initiate panic, error 5
Aborted (core dumped)
```
Backtrace shown as:
```
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1069
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1537
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:218
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:477
  11: rust_begin_unwind
             at src/libstd/panicking.rs:385
  12: core::panicking::panic_fmt
             at src/libcore/panicking.rs:89
  13: core::option::expect_none_failed
             at src/libcore/option.rs:1272
  14: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
  15: tokenizers::tokenizer::Tokenizer::train
  16: tokenizers::tokenizer::Tokenizer::train::{{closure}}
  17: tokenizers::tokenizer::__init11742626496714830824::__init11742626496714830824::__wrap
  18: <unknown>
  19: _PyEval_EvalFrameDefault
  20: <unknown>
  21: <unknown>
  22: <unknown>
  23: _PyEval_EvalFrameDefault
  24: <unknown>
  25: PyEval_EvalCode
  26: <unknown>
  27: <unknown>
  28: PyRun_InteractiveLoopFlags
  29: PyRun_AnyFileExFlags
  30: Py_Main
  31: main
  32: __libc_start_main
  33: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
I ran the full backtrace, it was too long, to post here, it is reproducible as shown above

**Comment by n1t0** [comment] 2020-07-17 23:39
Thanks for the complete reporting!

Duplicate of #322.

**Closed by n1t0** 2020-07-17 23:39 UTC
