### ISSUE TITLE
"Missing [UNK] token" error on WordLevel encode

### ISSUE THREAD

**Issue by juriwiens** [huggingface/tokenizers#351] opened 2020-07-21 15:44 UTC
Hi,

First of all thanks for this great library!

I'm using version `0.8.1rc1` with the goal to create a custom tokenizer that splits sequences at whitespaces. I've read all the related issues here and came up with this code, which uses the `WordLevel` model and works fine if a vocab is loaded that contains the unknown token:

```python
from tokenizers import Tokenizer
from tokenizers.models import WordLevel

unk_token = "<unk>"
vocab_file = "vocab.json"
with open(vocab_file, "w") as file:
    json.dump({unk_token: 0}, file)
Tokenizer(WordLevel(vocab_file, unk_token="<unk>")).encode("a b c")
```

But if I
- provide a vocab that doesn't contain the unknown token or
- do not provide a vocab at all

I'm getting a `Exception: WordLevel error: Missing [UNK] token from the vocabulary`.

```python
Tokenizer(WordLevel(None, unk_token=unk_token)).encode("a b c")
# => Exception: WordLevel error: Missing [UNK] token from the vocabulary
```

I’ve already digged into the code and tried to find or even fix the issue by myself, but since I have no rust experience, I have not completely succeeded. In any case, it is clear that the error is caused when the [unknown token is queried](https://github.com/huggingface/tokenizers/blob/58e29fd30c4f0b163f145b885732d970a3c387bc/tokenizers/src/models/wordlevel/mod.rs#L155-L156).

Strangely enough, adding the token beforehand does not solve the problem:

```python
tokenizer = Tokenizer(WordLevel(None, unk_token=unk_token))
print(tokenizer.get_vocab()) # => {}
tokenizer.add_tokens([unk_token])
tokenizer.add_special_tokens([unk_token])
print(tokenizer.get_vocab()) # => {'<unk>': 0}
tokenizer.encode("a b c") # => Exception: WordLevel error: Missing [UNK] token from the vocabulary
```

You might think: why would someone initialize a tokenizer without vocabulary? Since there is [no WordLevelTrainer implemented](https://github.com/huggingface/tokenizers/issues/265) at the moment, I create an own one in python that uses a "empty" WordLevel tokenizer to train the vocabulary initially. By the way, I'm using a temporary vocab file as workaround:

```python
        if vocab_file is None:
            special_tokens = [unk_token, bos_token, sep_token, pad_token]
            vocab_file = "_init_vocab.tmp.json"
            with open(vocab_file, "w") as file:
                json.dump({str(token) : i for i, token in enumerate(special_tokens)}, file)
                
        tokenizer = Tokenizer(WordLevel(vocab_file, unk_token=unk_token))
```

**Comment by joerenner** [comment] 2020-11-03 09:46
I get the same exception when trying to initialize a WordLevel with a vocab dictionary input argument to the init function (seems possible from https://github.com/huggingface/tokenizers/blob/bc19eaa186e0fd7e3de57406ce01a7e431a5740a/bindings/python/py_src/tokenizers/models/__init__.pyi#L141):

`
from tokenizers.models import WordLevel

m = WordLevel({"this": 0, "is": 1, "a": 2, "test": 3}, unk_token="[UNK]")
out = m.tokenize("unknown") # => Exception: WordLevel error: Missing [UNK] token from the vocabulary

`

**Comment by n1t0** [comment] 2020-11-03 11:16
> Missing "[UNK]" token from vocabulary. 

So why not add it to the vocabulary?
```
m = WordLevel({"this": 0, "is": 1, "a": 2, "test": 3, "[UNK]: 4}, unk_token="[UNK]")
```

**Comment by joerenner** [comment] 2020-11-03 12:47
> So why not add it to the vocabulary?

ah, yeah works for me. I was trying to use add_tokens() and kept getting the error, but adding it to the input works.

Thanks!

**Comment by Guitaricet** [comment] 2020-12-09 17:57
Hi! I am having the same issue and adding 'UNK' to the initial vocabulary does not seem to help.

Tokenizers version: `0.10.0rc1`

This is the code that reproduces the issue

```python
import tokenizers
from tokenizers.models import WordLevel
from tokenizers.pre_tokenizers import Whitespace

texts = ['a list of sentences from my dataset', 'this is a text with known words']
unk_token = '[UNK]'
tokenizer = tokenizers.Tokenizer(WordLevel({unk_token: 0}, unk_token=unk_token))
tokenizer.pre_tokenizer = Whitespace()

tokenizer.train_from_iterator(texts)

tokenizer.encode('this is a text with unknown_word')  # Exception: WordLevel error: Missing [UNK] token from the vocabulary
```

## Several workarounds I used that didn't work

1. Adding `tokenizer.add_special_tokens([unk_token])` after `from_from_iterator` does not seem to help either and adding it bore raises a cryptic `PanicException: called Result::unwrap() on an Err value: Any` (this actually happens because UNK is already provided in the initializer and it would be great if such case can be handled).

2. Another workaround is mentioned in the quickstart guide (version 0.9.4) is to save and load the tokenizer model, but it doesn't work either (at leas with a WordLevel model)

```python
# note that providing a different path to model.save raises
# No such file or directory error unless there is a
# preexisting directory for the tokenizer

files = tokenizer.model.save('.')
tokenizer.model = WordLevel.from_file(*files, unk_token="[UNK]")
```

3. Another thing I decided to try is to add an UNK token string to the training data. Does not help.

## The workaround that worked, but looks ugly

```python
import tokenizers
from tokenizers.models import WordLevel
from tokenizers.pre_tokenizers import Whitespace

texts = ['a list of sentences from my dataset', 'this is a text with known words']
unk_token = 'UNK'

pre_tokenizer = Whitespace()
tokenized_texts = [[w for w, _ in pre_tokenizer.pre_tokenize_str(t)] for t in texts]

vocabulary = {unk_token: 0}
for text in tokenized_texts:
    for token in text:
        if token in vocabulary: continue
        vocabulary[token] = len(vocabulary)

tokenizer = tokenizers.Tokenizer(WordLevel(token2id, unk_token))
tokenizer.pre_tokenizer = pre_tokenizer

e = tokenizer.encode('this is a text with unknown_word')
```

I personally think that this bug is important for several reasons. In my case, I want to include 🤗 Tokenizers to my NLP class so that students start to learn modern tools, but also this bug makes harder to quickly experiment with the non-BERT models.

I don't know Rust, but I'm a quick learner and would be happy to help solving this bug.

**Comment by n1t0** [comment] 2020-12-10 13:55
Hello @Guitaricet 

I'm sorry you had to try so many different things to make it work as you wanted. In your last workaround you actually reproduced the entire training, but you really shouldn't have to do this.

In your case, the issue is simply that you don't specify the special tokens you want to add in your vocabulary. Since you should be able to decide the order of said tokens, and so their associated IDs, we don't make any decision on your behalf (even if an unk token is specified).

In order to customize the training, you can specify a custom `Trainer`, here it will be a `WordLevelTrainer`:
```python
trainer = tokenizers.trainers.WordLevelTrainer(vocab_size=20000, special_tokens=["[PAD]", "[UNK]"])
tokenizer.train_from_iterator(iter, trainer=trainer)
```
You can find the API reference for said trainers here: https://huggingface.co/docs/tokenizers/python/master/api/reference.html#module-tokenizers.trainers

Using `train_from_iterator` works very similarly to the `train` method described in the guide, so the same logic applies and the examples should work exactly the same. We'll update it for the final 0.10.0 release.

The runtime exception looks like a bug indeed and should be fixed.

**Comment by n1t0** [comment] 2020-12-10 13:59
Also you might be interested in this: https://github.com/huggingface/tokenizers/blob/master/bindings/python/examples/train_with_datasets.py

It shows how to train using the `🤗 datasets` library that contains hundreds of datasets and metrics used in the field.

**Comment by Guitaricet** [comment] 2020-12-10 17:36
@n1t0 thank you for your answer!

I feel like the `special_tokens` part is a bit overcomplicated and I can't turn my had around it.

> Since you should be able to decide the order of said tokens, and so their associated IDs, we don't make any decision on your behalf (even if an unk token is specified).

This part makes sense after it is explained, but otherwise is pretty counterintuitive. It feels like there are many implicit connections that you should be aware of (am I right that you need to specify the `unk_token` several times - in `Model` and `Trainer` and it is impossible to train a tokenizer with UNK with a default trainer?). Also, doesn't the specifying initial vocabulary with `{unk_token: 0}` already provide an index for it?

Maybe, it would be useful to raise a warning if you call `train` on the tokenizer with a specified special tokens (but without special tokens provided to the trainer) that explains the issue and gives directors?

**Closed** 2021-01-06 19:57 UTC

**Comment by hemangjoshi37a** [comment] 2023-03-20 21:54
Is this already been solved? I having same   isseue rn.

**Comment by hemangjoshi37a** [comment] 2023-03-20 21:55
> ```python
> trainer = tokenizers.trainers.WordLevelTrainer(vocab_size=20000, special_tokens=["[PAD]", "[UNK]"])
> tokenizer.train_from_iterator(iter, trainer=trainer)
> ```

@n1t0 
this gives me this error :
```python
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[14], line 1
----> 1 trainer = tokenizer.trainers.WordLevelTrainer(vocab_size=20000, special_tokens=["[PAD]", "[UNK]"])
      2 tokenizer.train_from_iterator(iter, trainer=trainer)

AttributeError: 'BertTokenizerFast' object has no attribute 'trainers'
```
