### ISSUE TITLE
Exception: Custom PreTokenizer cannot be serialized

### ISSUE THREAD

**Issue by carter54** [huggingface/tokenizers#613] opened 2021-01-30 03:08 UTC
Hello~ I'm trying to train a BPE tokenizer with a customized pre_tokenizer.
The customized pre_tokenizer used a 3rd party package likes what has been shown in

https://github.com/huggingface/tokenizers/blob/dcb3bba235fc04895435c5f3e307327cdb80475b/bindings/python/examples/custom_components.py#L12

after training the tokenizer, I tried to use
```
tokenizer.save(tokenizer_path)
```
to save the tokenizer, but an Exception appeared:
```
Exception: Custom PreTokenizer cannot be serialized
```
I can see that a customized pre_tokenizer cannot be saved with the main tokenizer model, so I should save the main model individually. When loading the tokenizer, I should manually add the pre_tokenizer. Am I right?

**Comment by n1t0** [comment] 2021-01-30 15:06
Yes you are right, this is something that we'd like to support in the future though.

In the meantime you can either:
- save the model and then load everything back manually. If you don't have a complicated tokenizer with many special tokens and components it might be well suited
- use a "placeholder" PreTokenizer before saving your tokenizer, that you replace by your custom one after loading back.

**Comment by n1t0** [comment] 2021-02-03 14:52
Closing this as it is a duplicate of https://github.com/huggingface/tokenizers/issues/581.

**Closed by n1t0** 2021-02-03 14:52 UTC

**Comment by carter54** [comment] 2021-02-04 07:54
I see @n1t0  thx for the answer~
