### ISSUE TITLE
Facebook/bart-large-cnn tokenizer return offset mapping with duplicated tuple entries

### ISSUE THREAD

**Issue by chris-opendata** [huggingface/tokenizers#977] opened 2022-04-12 08:06 UTC
I am using the said pretrained tokenizer to tokenize cnn dailymail with an offset mapping return option. The reason is to make a token mask from the offset mapping. So, I don't expect any duplicated tuples. But I actually got two consecutive (104, 105) as follows. Is this a buggy behavour?

The source data:
> 'Successful cases were brought against government officials , against non-state actors like Radovan Karadžić in Bosnia-Herzegovina and against multinational corporations before the Second Circuit ruling in Kiobel that disallowed that .'

The encoded ids:
> [0, 42697, 2650, 1200, 58, 1146, 136, 168, 503, 2156, 136, 786, 12, 4897, 5552, 101, 7312, 22015, 4077, 625, 1277, 4726, 118, 4807, 11, 25305, 12, 13584, 329, 3733, 1417, 1243, 8, 136, 17043, 9053, 137, 5, 4665, 7813, 2255, 11, 11488, 2413, 523, 14, 2982, 34742, 14, 479, 2]

The returned offset mapping:
> [(0, 0), (0, 7), (7, 10), (11, 16), (17, 21), (22, 29), (30, 37), (38, 48), (49, 58), (59, 60), (61, 68), (69, 72), (72, 73), (73, 78), (79, 85), (86, 90), (91, 94), (94, 98), (99, 102), (102, 104), (104, 105), (104, 105), (105, 106), (106, 107), (108, 110), (111, 117), (117, 118), (118, 121), (121, 122), (122, 124), (124, 126), (126, 129), (130, 133), (134, 141), (142, 155), (156, 168), (169, 175), (176, 179), (180, 186), (187, 194), (195, 201), (202, 204), (205, 207), (207, 209), (209, 211), (212, 216), (217, 220), (220, 227), (228, 232), (233, 234), (0, 0)]

Thanks

**Comment by Narsil** [comment] 2022-04-12 09:11
Hi @chris-opendata totally not a bug ! 

The culprit here is : `ž`.

This is a single unicode codepoint, `(104, 105)` here, but it actually is represented as two distinct tokens by the tokenizer, because the tokenizer uses `ByteLevel` so it does decompose this single codepoint into two tokens each taking part of the bytes.

You can check:

```python
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("facebook/bart-large-cnn")
tokenizer.decode([1277, 4726])
# 'ž', as expected
tokenizer.decode([1277])
# '�' These are actually bytes which cannot be represented as a string, the glyph is used for invalid utf-8 data
tokenizer.decode([4726])
# '�' 
```

Does that answer your question ?

**Comment by Narsil** [comment] 2022-04-12 12:32
There are many cases.

You basically can't really assume anything about what are the "cases".
Offsets can be zero-width (inserted token like BOS, CLS for instance).
Offsets can contain holes (they can be abritrarily large), can overlap or even be duplicates (like here).

What offsets provide:
- A consistent way to know "where does the token comes from" ? (`original_sentence[start:stop]` IS the reason for `id` being there)
- The offsets should be a increasing series (with maybe duplicates like here)

**Comment by chris-opendata** [comment] 2022-04-12 12:46
> There are many cases.
> 
> You basically can't really assume anything about what are the "cases". Offsets can be zero-width (inserted token like BOS, CLS for instance). Offsets can contain holes (they can be abritrarily large), can overlap or even be duplicates (like here).
> 
> What offsets provide:
> 
> * A consistent way to know "where does the token comes from" ? (`original_sentence[start:stop]` IS the reason for `id` being there)
> * The offsets should be a increasing series (with maybe duplicates like here)


You are right. I actually hit another case where the preceding span (26, 28) covers the following span (27, 28) as follows. I am just wondering what is a generic and reliable way to make a token mask out of something like offset mapping. Maybe I somehow get the tokenizer to return the tokenized string from which I may work out a token mask by relying on the leading "##" of subtokens? Appreciate any suggestion. Thank you.

> 'The Arabic hashtag -- #الراتب_مايكفي_الحاجة ( loosely translated as " the salary does not meet my needs " ) -- reached 17 million tweets in the first two weeks .'

> [0, 133, 19645, 15493, 480, 849, 43321, 29434, 34955, 10278, 41117, 1215, 33070, 29438, 26174, 26068, 862, 26068, 10172, 26174, 1215, 43321, 21593, 12410, 34955, 11582, 38419, 36, 29213, 16877, 25, 22, 5, 5391, 473, 45, 972, 127, 782, 22, 4839, 480, 1348, 601, 153, 6245, 11, 5, 78, 80, 688, 479, 2]

> [(0, 0), (0, 3), (4, 10), (11, 18), (19, 21), (22, 23), (23, 25), (25, 26), (26, 28), (27, 28), (28, 29), (29, 30), (30, 31), (31, 32), (32, 33), (33, 34), (33, 34), (34, 35), (34, 35), (35, 36), (36, 37), (37, 39), (39, 40), (39, 40), (40, 42), (41, 42), (42, 43), (44, 45), (46, 53), (54, 64), (65, 67), (68, 69), (70, 73), (74, 80), (81, 85), (86, 89), (90, 94), (95, 97), (98, 103), (104, 105), (106, 107), (108, 110), (111, 118), (119, 121), (122, 129), (130, 136), (137, 139), (140, 143), (144, 149), (150, 153), (154, 159), (160, 161), (0, 0)]

**Comment by Narsil** [comment] 2022-04-12 13:51
> what is a generic and reliable way to make a token mask out of something like offset mapping. 

I am not sure what is your intent here.

You want to modify the input string in order to create a mask in the input ids ? You cannot do that in general basically.
If you want to create a mask, you need to work directly in ID space. (update the ids directly to become the ID for the mask)

The offsets are actually used to "mark" the answer provided by `question-answering` models for instance.

For all IDs marked as `answer` by the model, take the smallest `start` and the biggest `stop` and there you get a nice marked area of the input text. (There is no AFAIK model that does that token per token, where the answer might itself contain holes, but the offset would allow that to be OK too)

**Comment by chris-opendata** [comment] 2022-04-13 00:37
> > what is a generic and reliable way to make a token mask out of something like offset mapping.
> 
> I am not sure what is your intent here.
> 
> You want to modify the input string in order to create a mask in the input ids ? You cannot do that in general basically. If you want to create a mask, you need to work directly in ID space. (update the ids directly to become the ID for the mask)
> 
> The offsets are actually used to "mark" the answer provided by `question-answering` models for instance.
> 
> For all IDs marked as `answer` by the model, take the smallest `start` and the biggest `stop` and there you get a nice marked area of the input text. (There is no AFAIK model that does that token per token, where the answer might itself contain holes, but the offset would allow that to be OK too)

Thank you for your reply. My user case is for latent states working with dependency parsing structure from corenlp tool which is word based. As an approach of using the starting subtoken to represent a word seen in articles, I need to create such a masking to mark the starting subtokens in the sequence. It seems that there is no generic way to do it for a sequence. I maybe create an individual mask by encoding word by word instead of the whole sequence since I can know the starting subtoken (always zero) and the number of subtokens. I can then create a sequence mask by concatenating them. But it would be a very slow process to tokenize a whole dataset. No sure if there is any pitfall of the approach or a better way to do it. Thank you.

**Comment by Narsil** [comment] 2022-04-13 08:26
> I need to create such a masking to mark the starting subtokens in the sequence.

If I understand correctly, what you want is to know what tokens(ids) are representing the start of a word.
Then I think you should be OK with offsets, but you need to understand that tokens(ids) are not necessarily correlated with words so you need to find ways to handle misalignment most likely.

(Everything in quote, and intentionnally not using "subtoken" since those concepts are just confusing when trying to deal with tokenizers in general)
Let's say you have the corenlp offsets of what it considers words, then, to find the "first" token of each "word" would be:
the first offsets that overlap (`start<= start_of_word and stop >= start_of_word`) will be what you want.

Since tokens(ids) are ordered, then the first id necessarily corresponds to what you want.
Please note that the `start` and `start_of_word` might be different
Also that it might be a zero-width token (you need to check on real data, you might want to stick with non zero-width tokens matching but that could depend on the tokenizer).
Also note, that such a token might not exist (since tokenizers can arbitrarily skip data when producing tokens(ids) ).

But with that you should get the closest thing that you want, which will probably work on most English+space separated languages. For stuff like German or Chinese (any non space separated langage), you will probably encounter more issues. I *think* the rule I wrote holds, but I can't be sure.

**Comment by chris-opendata** [comment] 2022-04-14 07:48
> (Everything in quote, and intentionnally not using "subtoken" since those concepts are just confusing when trying to deal with tokenizers in general) Let's say you have the corenlp offsets of what it considers words, then, to find the "first" token of each "word" would be: the first offsets that overlap (`start<= start_of_word and stop >= start_of_word`) will be what you want.

Brilliant. This is a simple enough rule.

> Since tokens(ids) are ordered, then the first id necessarily corresponds to what you want. Please note that the `start` and `start_of_word` might be different Also that it might be a zero-width token (you need to check on real data, you might want to stick with non zero-width tokens matching but that could depend on the tokenizer). Also note, that such a token might not exist (since tokenizers can arbitrarily skip data when producing tokens(ids) ).

I assume that zero-width tokens are predefined special tokens (BOS, EOS,...) on the sequence boundary. So, I guess that I should ignore such tokens otherwise.

> But with that you should get the closest thing that you want, which will probably work on most English+space separated languages. For stuff like German or Chinese (any non space separated langage), you will probably encounter more issues. I _think_ the rule I wrote holds, but I can't be sure.

I am using pretrained BART tokenizer Fast (byte-pair encoding) for CNN DM dataset. It's mainly English but may mix with other language occasionally as seen. But I expect that they should not have statistical significance even if misaligned a few times as long as they don't break the training run.

Much appreciated for your detailing suggestion.

**Comment by Narsil** [comment] 2022-04-14 08:36
Cheers ! 

Closing this, don't hesitate to re-open if you think this wasn't solved.

**Closed by Narsil** 2022-04-14 08:36 UTC

**Comment by chris-opendata** [comment] 2022-04-14 08:40
Thanks.
