### ISSUE TITLE
Tokens to Words mapping in the tokenizer decode step?

### ISSUE THREAD

**Issue by dvirginz** [huggingface/tokenizers#447] opened 2020-10-02 05:49 UTC
Is there a way to know the mapping from the tokens back to the original words in the `tokenizer.decode()` function?<br>
For example:

```python
from transformers.tokenization_roberta import RobertaTokenizer

tokenizer = RobertaTokenizer.from_pretrained('roberta-large', do_lower_case=True)

str = "This is a tokenization example"
tokenized = tokenizer.tokenize(str) 
## ['this', 'Ġis', 'Ġa', 'Ġtoken', 'ization', 'Ġexample']

encoded = tokenizer.encode_plus(str) 
## encoded['input_ids']=[0, 42, 16, 10, 19233, 1938, 1246, 2]
    
decoded = tokenizer.decode(encoded['input_ids']) 
## '<s> this is a tokenization example</s>'
```
And the objective is to have a function that maps each token in the `decode` process to the correct input word, for the above example it will be:<br>
`desired_output = [[1],[2],[3],[4,5],[6]]`<br> As `this` corresponds to id `42`, while `token` and `ization` corresponds to ids `[19244,1938]` which are at indexes `4,5` of the `input_ids` array.

**Comment by Narsil** [comment] 2020-10-02 09:45
Hi @dvirginz you are using the "slow" tokenizers from transformers. In tokenizers ("fast"), you can do something similar to what you want.

```python
str = "This is a tokenization example"
encoded = tokenizer.encode(str) 
## Encoding(num_tokens=4, attributes=[ids, type_ids, tokens, offsets, attention_mask, special_tokens_mask, overflowing])

encoded.ids
## [0, 42, 16, 10, 19233, 1938, 1246, 2]

encoded.offsets
## [(0, 4), (4, 7), (7, 9), (9, 13), ....]

str[0:4] == "This"
str[4:7] == " is"
str[7:9] == " a"
str[9:13] == " token"
str[...]  == "ization"
```

This is a bit more general to what you propose as the concept of a "word" does not necessarily make sense in the tokenization process. This should however be enough for you to achieve what you want.

As a side note, I think RobertaFast are not yet in `transformers` so you're probably going to need to wait a little, or compile from master to achieve what I mentionned for `roberta-large` tokenizer.

**Comment by n1t0** [comment] 2020-10-02 14:03
Hi @dvirginz! Thank you for your answer @Narsil! We can indeed achieve this using the offsets, but we also provide some more mappings that might be easier to use in this case.

With `tokenizers` (this assumes a tokenizer equivalent to the one used with roberta):
```python
str = "This is a tokenization example"
encoded = tokenizer.encode(str)
## Encoding(num_tokens=8, attributes=[ids, type_ids, tokens, offsets, attention_mask, special_tokens_mask, overflowing])

# Check the full mapping token -> word:
encoded.words
## [None, 0, 1, 2, 3, 3, 4, None]

# Build your desired mapping
desired_output = []
for word_id in encoded.words:
    if word_id is not None:
        start, end = encoded.word_to_tokens(word_id)
        desired_output.append((start, end))
desired_output
## [(1, 2), (2, 3), (3, 4), (4, 6), (4, 6), (6, 7)]
```
And you can achieve the same with `transformers`:
```python
from transformers import AutoTokenizer, RobertaTokenizerFast

# These are similar ways of loading a fast Roberta tokenizer
tokenizer = AutoTokenizer.from_pretrained("roberta-large", use_fast=True)
# Or
tokenizer = RobertaTokenizerFast.from_pretrained("roberta-large")

str = "This is a tokenization example"
encoded = tokenizer(str)

# Check the full mapping token -> word:
encoded.words()
## [None, 0, 1, 2, 3, 3, 4, None]

# Build your desired mapping
desired_output = []
for word_id in encoded.words():
    if word_id is not None:
        start, end = encoded.word_to_tokens(word_id)
        desired_output.append((start, end))
desired_output
## [(1, 2), (2, 3), (3, 4), (4, 6), (4, 6), (6, 7)]
```

The output is a little bit different than what you asked exactly since it uses spans to limit to 2 values (start end end), but you can easily build it using the same method.

Side note: In `transformers` when you `encode`, you get a `BatchEncoding` (cf [the documentation](https://huggingface.co/transformers/main_classes/tokenizer.html#transformers.BatchEncoding)) and you can access the output of `tokenizers` (cf [tokenizers.Encoding](https://github.com/huggingface/tokenizers/blob/a410903/bindings/python/py_src/tokenizers/__init__.pyi#L257-L422))  by sub-scripting it (using the index in the batch):
```
encoded = tokenizer(str)
tokenizers_output = encoded[0]
## Encoding(num_tokens=8, attributes=[ids, type_ids, tokens, offsets, attention_mask, special_tokens_mask, overflowing])
```

**Comment by dvirginz** [comment] 2020-10-02 14:23
Black magic!
I wasn't aware of the `.words` field at all (although it made perfect sense for me to store one in the encoding step).

Thanks a lot:)

**Comment by n1t0** [comment] 2020-10-02 14:40
Awesome, glad it helped! I'm closing this issue, but feel free to reopen it if needed.

**Closed by n1t0** 2020-10-02 14:40 UTC

**Comment by pzelasko** [comment] 2021-02-24 19:17
It seems like this does not work with `'s` (as in `how's`) - does the tokenizer consider it as a separate word for some specific reason?

Reproduce with:
```python
tok = AutoTokenizer.from_pretrained('allenai/longformer-base-4096')
x = tok("hey how's it going")

print(x.word_ids(0))
# [None, 0, 1, 2, 3, 4, None]

print([tok.decode([i]) for i in tok.encode("hey how's it going")])
# ['<s>', 'hey', ' how', "'s", ' it', ' going', '</s>']  <-- note no leading whitespace before 's
```
