### ISSUE TITLE
XLM tokenizer?

### ISSUE THREAD

**Issue by mkumar10** [huggingface/tokenizers#251] opened 2020-04-26 21:03 UTC
I was wondering if this supports the tokenizer for XLM as well? Seems like the original tokenizer uses sacremoses - and can we expect that to be incorporated in this repo?

**Comment by larochef** [comment] 2023-05-03 09:38
Anything new on this? I'd also need to use flaubert and I would prefer to use the huggingface tokenizers

**Comment by Narsil** [comment] 2023-05-03 10:55
XLM is not flaubert, but both are possible with this lib.

```python
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("flaubert/flaubert_base_uncased")
```

`tokenizer.save_pretrained("local")`  if you want to have the actual `tokenizers` file.

**Comment by larochef** [comment] 2023-05-03 12:30
Thx for the tip, I will give it a try. I thought Flaubert needed a bpe tokenizer to work.

**Comment by Narsil** [comment] 2023-05-03 12:39
I don't see any issues. Please provide steps to reproduce.

**Comment by larochef** [comment] 2023-05-03 12:43
I will try to create a small repo with minimal code, the real code I run uses djl, which has java bindings on the rust code

**Comment by Narsil** [comment] 2023-05-03 12:51
Maybe it's just the actual tokenizer you're using, if it's on the hub, I can take a look.

**Comment by larochef** [comment] 2023-05-03 13:11
In fact I could reroduce it with little code, maybe I am not using the correct apis at some point, here is the code:

```rust
use tokenizers::models::bpe::BPE;
use tokenizers::Tokenizer;

fn main() {
    match BPE::from_file(
        "tokenizer/vocab.json",
        "tokenizer/merges.txt"
    ).build() {
        Ok(model) => {
            let tokenizer = Tokenizer::new(model);
            match tokenizer.encode("Bonjour, le monde", false) {
                Ok(_) => println!("Tokenization successful"),
                Err(err) => println!("Tokenization failed: {}", err),
            }
        }
        Err(err) => println!("Creating tokenizer failed: {}", err)
    }
    println!("Done");
}
```

in order to work there needs to be the vocab.json and merges.txt in a tokenizer directory.

Am I doing anything wrong ?

**Comment by larochef** [comment] 2023-05-03 13:19
@Narsil I also created a repo with the code: https://github.com/numind-tech/flaubert_tokenizer

**Comment by Narsil** [comment] 2023-05-03 13:20
> Am I doing anything wrong ?

Possibly, this is disrespecting all components except the model BPE. Most tokenizers use `normalizer`, a `pre_tokenizer` etc...
Usually the easiest is doing `let tokenizer = Tokenizer::from_file("tokenizer.json")`.

But here you're showing a rust example, the original issue was mentionning python world.
Can you create a new issue and provide all the details.
- Steps to reproduce
- What you expect
- What you got instead.

**Comment by larochef** [comment] 2023-05-03 13:24
thanks for the answer, I will do it

**Comment by Narsil** [comment] 2023-05-03 13:34
Closing this since is is too old.

**Closed by Narsil** 2023-05-03 13:34 UTC

**Comment by xenova** [comment] 2023-09-07 02:36
I know this issue is quite old, but considering that `sacremoses` is still relatively popular (2.2m downloads last month, [source](https://www.pepy.tech/projects/sacremoses)), perhaps it's worth a second look at adding support for it in `tokenizers`?

My use-case is getting this class of tokenizers running in [transformers.js](https://github.com/xenova/transformers.js), which relies on having a tokenizer.json file.

**Comment by Narsil** [comment] 2023-09-07 07:06
> I have noticed that HerBERT tokenizers also rely on sacremoses, but they do have a Fast implementation. Would it not be similar to extend/duplicate this functionality for the other similar tokenizers (like XLM tokenizer?)

This looks promising indeed all the rewrite rules are contained in the fast tokenizer: https://github.com/huggingface/transformers/blob/main/src/transformers/models/herbert/tokenization_herbert.py vs https://github.com/huggingface/transformers/blob/main/src/transformers/models/herbert/tokenization_herbert_fast.py

However it's not the full sacremoses.

I personally don't think it's the most impactful thing I could do to support fully sacremoses (I'm pretty sure you can get 80% done relatively fast, but the last 20% are going to be painful).

If you're interested in doing so you're more than welcome, it looks like sacremoses is "mostly" a normalizer and regexp heavy.
But we would need a very strong test suite to make sure everything is compliant. And that's kind of hard to do/prove.

Here is what I had to do for SPM (and couldn't get 100% all the way)

>  is still relatively popular (2.2m downloads last month

Pretty weak argument in my opinion, as there can be other users outside of ML or the context of this lib usage. So a more relevant metric imo would be to have some kind of hf.co download metric vs other same period models (or MTEB leaderboard ranking). Anything that would make moses both relevant AND  implying that an implementation here would have some impact (because unlocking use cases outside of python for instance).

**Comment by xenova** [comment] 2023-09-07 21:39
> (I'm pretty sure you can get 80% done relatively fast, but the last 20% are going to be painful).

Yes this was my thought too. Looking at their rewrite rules looks highly complex to say the least.

> > is still relatively popular (2.2m downloads last month

> Pretty weak argument in my opinion, as there can be other users outside of ML or the context of this lib usage. 

Indeed the `XLM` download metrics on the hub aren't very high these days: e.g., https://huggingface.co/xlm-clm-ende-1024 has 22k in the past month, which although isn't nothing, is a far stretch from some of the more up-to-date models. It has 688 648 downloads in total, but this definitely shows it's getting less popular these days. Anyway, just thought I'd mention it, but I do agree with you, there are probably better things to spend one's time on.

Maybe there are other `sacremoses` models which are more popular than `xlm`.
