### ISSUE TITLE
Progress not getting displayed while training ByteLevelBPETokenizer

### ISSUE THREAD

**Issue by sayakpaul** [huggingface/tokenizers#304] opened 2020-06-13 05:07 UTC
I am training a `ByteLevelBPETokenizer` and while training it the progress is not getting displayed even though I have explicitly set `show_progress=True`. Here's the [Colab Notebook](https://colab.research.google.com/gist/sayakpaul/939b16bb4d5376822a46089bd52e0bd8/tokenization.ipynb) that can reproduce this issue.

**Comment by n1t0** [comment] 2020-06-15 12:35
Thank you for reporting this @sayakpaul. This is a known limitation of the library we use to show progress.
Closing this, as it is a duplicate of https://github.com/huggingface/tokenizers/issues/157

**Closed by n1t0** 2020-06-15 12:35 UTC
