### ISSUE TITLE
Conda installation is broken

### ISSUE THREAD

**Issue by jplu** [huggingface/tokenizers#1121] opened 2022-12-16 14:43 UTC
Hi,

The conda package from the huggingface conda repository is broken on Debian-like Linux. It seems to be compiled with "Red Hat"-like Linux and then fails to find the proper `libssl.so` to properly run on Debian-like Linux. The raised error is:
```
Traceback (most recent call last):
  File "/home/jplu/anaconda3/envs/transformers/lib/python3.9/site-packages/transformers/utils/import_utils.py", line 1093, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "/home/jplu/anaconda3/envs/transformers/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/jplu/anaconda3/envs/transformers/lib/python3.9/site-packages/transformers/models/__init__.py", line 19, in <module>
    from . import (
  File "/home/jplu/anaconda3/envs/transformers/lib/python3.9/site-packages/transformers/models/mt5/__init__.py", line 40, in <module>
    from ..t5.tokenization_t5_fast import T5TokenizerFast
  File "/home/jplu/anaconda3/envs/transformers/lib/python3.9/site-packages/transformers/models/t5/tokenization_t5_fast.py", line 24, in <module>
    from ...tokenization_utils_fast import PreTrainedTokenizerFast
  File "/home/jplu/anaconda3/envs/transformers/lib/python3.9/site-packages/transformers/tokenization_utils_fast.py", line 25, in <module>
    import tokenizers.pre_tokenizers as pre_tokenizers_fast
  File "/home/jplu/anaconda3/envs/transformers/lib/python3.9/site-packages/tokenizers/__init__.py", line 79, in <module>
    from .tokenizers import (
ImportError: libssl.so.10: cannot open shared object file: No such file or directory

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/jplu/dev/buster/indexing-benchmark/to_qdrant.py", line 1, in <module>
    from transformers import AutoTokenizer
  File "<frozen importlib._bootstrap>", line 1055, in _handle_fromlist
  File "/home/jplu/anaconda3/envs/transformers/lib/python3.9/site-packages/transformers/utils/import_utils.py", line 1083, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "/home/jplu/anaconda3/envs/transformers/lib/python3.9/site-packages/transformers/utils/import_utils.py", line 1095, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.models.auto because of the following error (look up to see its traceback):
libssl.so.10: cannot open shared object file: No such file or directory
```
The conda install command is:
```
conda install -c huggingface transformers
```

When installing the `tokenizers` package from the `conda-forge` repository it works as expected.

**Comment by Narsil** [comment] 2022-12-19 10:26
Indeed.

Keep in mind the `conda-forge` version is a bit outdated compared to the `huggingface` one.
For some reason the libssl link is broken on more recent version, I'll investigate.

**Comment by Narsil** [comment] 2022-12-19 12:01
Should be good now ! 

Thanks for creating this issue, I'll wait for confirmation before closing this.

**Closed** 2022-12-19 12:50 UTC

**Comment by jplu** [comment] 2022-12-19 12:52
@Narsil Thanks for the fix. Nevertheless, the new version is not compliant with Python 3.10 now:
```
- tokenizers=0.13.2 -> python[version='>=3.7,<3.8.0a0|>=3.8,<3.9.0a0|>=3.9,<3.10.0a0']
```

**Comment by jplu** [comment] 2022-12-19 13:26
Humm but it looks to be available for Windows and OSX in 3.10 (accordingly to the anaconda repo https://anaconda.org/HuggingFace/tokenizers/files?version=0.13.2), why not Linux?

I will pass by pip in the meantime, but it will not be properly compliant with our usual conda env deployment.

**Comment by Narsil** [comment] 2022-12-19 13:58
Because for those we can use a GH action.: https://github.com/huggingface/tokenizers/blob/main/.github/workflows/python-release-conda.yml

I'm not really sure why Linux doesn't use it but I'm pretty sure it's about libc support (basically to cover a wide spectrum of linux, you need to have a relatively old/standard glibc). https://github.com/huggingface/tokenizers/pull/856/files

I'm not really willing to invest too much time into figuring out if the issue is solved or not by conda now, especially since the platforms where it fails are not necessarily the most standard ones, so it usually takes a while before we notice about such issues.

**Comment by Narsil** [comment] 2022-12-19 14:00
https://github.com/huggingface/tokenizers/issues/585

**Comment by jplu** [comment] 2022-12-19 14:25
Humm I see, I do understand :ok_hand:  Just by curiosity, why not moving from Ubuntu 18.04 to 20.04 or even 22.04? Since Ubuntu 18.04 will not even be supported from next April.

**Comment by Narsil** [comment] 2022-12-19 14:33
What do you mean ? This is not about ubuntu.

**Comment by jplu** [comment] 2022-12-19 14:46
From here https://github.com/huggingface/tokenizers/blob/main/.github/workflows/python-release-conda.yml#L62 I see it runs on Ubuntu 18.04, I guess, certainly to fix #585 and then satisfy the old glibc version. My question is (maybe I'm wrong), is-it possible to add a new `build_and_package` job for Python >=3.10 (or only ==3.10) with Ubuntu 20.04 as from this version, glibc is 2.36 which is the new default for the new many Linux releases since two years.

**Comment by Narsil** [comment] 2022-12-20 12:16
Actually we're just running in a container `container: quay.io/pypa/manylinux2014_x86_64` which is the one doing the build.

This container is done exactly for the purpose of providing portable binaries across linux distributions (which ubuntu isn't).
Since pypi doesn't differentiate linux based on distribution, this is the only way to get portable binaries for linux.

`ubuntu` only means it's running the docker runner, so it shouldn't be too relevant.

**Comment by jplu** [comment] 2022-12-20 17:48
OK I see! Thanks for the explanation.
