### ISSUE TITLE
wasm as compiler target for browser support

### ISSUE THREAD

**Issue by lhk** [huggingface/tokenizers#245] opened 2020-04-22 11:15 UTC
It would be great to be able to use this code on the client, or on-device in a hybrid app.

Since I've never compiled Rust to wasm myself, I'm not aware of the limitations :)
From a quick web search, io and threading seem to be off-limits.
Would it be feasible to add wasm as a compilation target to this library?

**Comment by n1t0** [comment] 2020-04-22 15:17
Hi @lhk, thank you for your interest in `tokenizers`!
I agree with you that wasm support would be great. Unfortunately, it is not as easy as adding a compilation target. We would have to write bindings and find a way to deal with the missing features somehow. I'd be more than happy to get and review a PR from someone on this subject as I unfortunately don't have the bandwidth to do it myself at the moment.

This issue is a duplicate of https://github.com/huggingface/tokenizers/issues/63

**Closed by n1t0** 2020-04-22 15:17 UTC

**Comment by lhk** [comment] 2020-04-22 19:45
thanks for the quick feedback.
I'm very sorry, that I missed the duplicate. For some reason I only searched for wasm and forgot to check WebAssembly.
